#!/usr/bin/env python3
"""Validate a decomposition plan.json and render the Stop-2 review markdown.

plan.json (schema: references/plan-json-schema.md) is the single source of
truth; the decomposition-plan-<flow>.md that users review at Stop 2 is a
RENDERED VIEW generated by this script (per references/decomposition-plan-
format.md), never hand-written. That kills md/json divergence and cuts the
architect's write-token volume to the design fields only.

Validation is a hard gate: structural issues, step-range errors, unbuildable
wiring, and lineage-closure violations (computed by scripts/plan_model.py —
the SAME implementation build_from_plan.py builds with) abort the render, so
a plan that renders is a plan that builds.

Usage:
    python render_plan_md.py --plan reports/decomposition-plan-<flow>.json \
        --source <original>.tfl -o reports/decomposition-plan-<flow>.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from flow_io import inspect_input_node, load_flow_json  # noqa: E402
from plan_model import (  # noqa: E402
    StepResolver,
    compute_flow_graph,
    load_plan,
    validate_plan_with_source,
)

LAYER_LABEL = {"staging": "stg", "intermediate": "int", "marts": "marts"}


def read_source(path: Path) -> dict:
    if path.suffix in (".tfl", ".tflx"):
        return load_flow_json(path)
    return json.loads(path.read_text(encoding="utf-8"))


def flow_waves(plan: dict) -> list[list[dict]]:
    """Topological levels of plan flows by upstream_pds dependency (the same
    ordering publish/run must follow)."""
    flows = plan["flows"]
    by_name = {f["name"]: f for f in flows}
    deps: dict[str, set[str]] = {}
    for f in flows:
        d = set()
        for inp in f.get("inputs", []) or []:
            if inp.get("kind") == "upstream_pds" and inp["pds_name"] in by_name:
                d.add(inp["pds_name"])
        deps[f["name"]] = d
    waves: list[list[dict]] = []
    placed: set[str] = set()
    remaining = [f["name"] for f in flows]
    while remaining:
        ready = [n for n in remaining if deps[n] <= placed]
        if not ready:  # cycle — validation already flags unbuildable wiring
            ready = remaining[:]
        waves.append([by_name[n] for n in ready])
        placed.update(ready)
        remaining = [n for n in remaining if n not in placed]
    return waves


def mermaid_id(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name)


def render_before_dag(resolver: StepResolver, plan: dict) -> list[str]:
    """Before-DAG limited to the format's '主要な分岐点': inputs, outputs,
    branch/merge nodes, Join/Union, and split-referenced steps."""
    src_nodes = resolver.flow["nodes"]
    split_steps = {sp["step"] for f in plan["flows"]
                   for sp in (f.get("splits") or [])}
    prev_count: dict[str, int] = {nid: 0 for nid in src_nodes}
    for n in src_nodes.values():
        for nx in n.get("nextNodes", []) or []:
            cid = nx.get("nextNodeId")
            if cid in prev_count:
                prev_count[cid] += 1

    def selected(nid: str) -> bool:
        n = src_nodes[nid]
        ntype = (n.get("nodeType") or "").split(".")[-1]
        return (
            n.get("baseType") in ("input", "output")
            or ntype in ("SuperJoin", "SuperUnion")
            or prev_count[nid] > 1
            or len(n.get("nextNodes") or []) > 1
            or resolver.step_by_uuid[nid] in split_steps
        )

    sel = [nid for nid in resolver.order if selected(nid)]
    L = []
    for nid in sel:
        n = src_nodes[nid]
        step = resolver.step_by_uuid[nid]
        ntype = (n.get("nodeType") or "").split(".")[-1]
        label = f'#{step} {ntype} {(n.get("name") or "?")}'.replace('"', "'")
        if n.get("baseType") in ("input", "output"):
            L.append(f'  n{step}[/"{label}"/]')
        else:
            L.append(f'  n{step}["{label}"]')
    L.append("")
    sel_set = set(sel)
    for nid in sel:
        # contract chains: walk forward through unselected nodes
        stack = [c.get("nextNodeId") for c in src_nodes[nid].get("nextNodes") or []]
        seen: set[str] = set()
        while stack:
            cur = stack.pop()
            if not cur or cur in seen or cur not in src_nodes:
                continue
            seen.add(cur)
            if cur in sel_set:
                L.append(f"  n{resolver.step_by_uuid[nid]} --> n{resolver.step_by_uuid[cur]}")
            else:
                stack.extend(c.get("nextNodeId")
                             for c in src_nodes[cur].get("nextNodes") or [])
    return L


def render_after_dag(plan: dict, resolver: StepResolver) -> list[str]:
    L: list[str] = []
    edges: list[str] = []
    ext_sources: dict[str, str] = {}  # mermaid id -> label
    for f in plan["flows"]:
        fid = mermaid_id(f["name"])
        L.append(f'  {fid}[{f["name"]}]')
        if f["kind"] == "pds_augment":
            info = inspect_input_node(resolver.flow,
                                      resolver.uuid(f["source_input_step"]))
            cap = info.get("vconn_caption") or "source"
            sid = "src_" + mermaid_id(cap)
            ext_sources[sid] = f"{cap} (Virtual Connection)"
            edges.append(f"  {sid} --> {fid}")
            continue
        for inp in f.get("inputs", []) or []:
            if inp["kind"] == "upstream_pds":
                edges.append(f"  {mermaid_id(inp['pds_name'])} --> {fid}")
            elif inp["kind"] == "passthrough_pds":
                sid = "src_" + mermaid_id(inp["pds_name"])
                ext_sources[sid] = f"{inp['pds_name']} (PDS passthrough)"
                edges.append(f"  {sid} --> {fid}")
            else:  # transplant
                node = resolver.node(inp["step"])
                sid = "src_" + mermaid_id(node.get("name") or f"step{inp['step']}")
                ext_sources[sid] = node.get("name") or f"step {inp['step']}"
                edges.append(f"  {sid} --> {fid}")
    header = [f'  {sid}[/"{label}"/]'.replace('"', '"')
              for sid, label in ext_sources.items()]
    return header + L + [""] + edges


def render_entry(f: dict, resolver: StepResolver, plan: dict) -> list[str]:
    L = [f"### {f['name']}", ""]
    L.append(f"- **Layer**: {f['layer']}")
    if f.get("input_status") == "needs_provisioning":
        prov = f.get("provisioning") or {}
        L.append("- **Input status**: `needs_provisioning` — build を skip "
                 "(下記 [Input provisioning required](#input-provisioning-required))")
        L.append(f"- **Source**: {prov.get('source', '?')} ({prov.get('kind', '?')})")
        L.append(f"- **Description**:\n  {f.get('description', '')}")
        L.append("")
        return L
    if f["kind"] == "pds_augment":
        info = inspect_input_node(resolver.flow,
                                  resolver.uuid(f["source_input_step"]))
        L.append("- **Materialization**: `live_pds` (prep-pds-augmenter で publish、"
                 "run フェーズなし)")
        L.append("- **Inputs**:")
        L.append(f"  - Source: `{info.get('vconn_caption')}` (仮想接続) / "
                 f"`{info.get('table_name')}` テーブル "
                 f"(元 Input {resolver.label(f['source_input_step'])})")
        L.append("- **Outputs**:")
        L.append("  - Type: Published Data Source (Live)")
        L.append(f"  - Name: `{f['name']}`")
        L.append(f"  - Target project: `{plan['ds_projects']['staging']['path']}`")
        L.append("- **Transforms (column-level)**:")
        L.append("  | op | column_name | to_caption | to_datatype |")
        L.append("  |---|---|---|---|")
        for t in f.get("transforms", []):
            L.append(
                f"  | {t['op']} | `{t['column_name']}` "
                f"| {t.get('to_caption') or '—'} | {t.get('to_datatype') or '—'} |")
        L.append(f"- **Description**:\n  {f.get('description', '')}")
        L.append("")
        return L

    graph = compute_flow_graph(f, resolver, plan)
    L.append("- **Inputs**:")
    for inp in f.get("inputs", []) or []:
        if inp["kind"] == "upstream_pds":
            L.append(f"  - Published DS: `{inp['pds_name']}` "
                     f"(本 plan の {LAYER_LABEL.get(next((x['layer'] for x in plan['flows'] if x['name'] == inp['pds_name']), 'staging'))} が publish)")
        elif inp["kind"] == "passthrough_pds":
            L.append(f"  - Published DS: `{inp['pds_name']}` "
                     "(**passthrough from source flow**)")
            L.append(f"    - Project path: `{inp['project_path']}`")
            L.append(f"    - LUID: `{inp['luid']}`")
        else:
            node = resolver.node(inp["step"])
            L.append(f"  - Transplant: 元 Input {resolver.label(inp['step'])} "
                     f"({node.get('nodeType', '?').split('.')[-1]} をそのまま転写)")
    L.append("- **Outputs**:")
    L.append("  - Type: Published Data Source")
    L.append(f"  - Name: `{f['output']['name']}`")
    L.append(f"  - Target project: `{plan['ds_projects'][f['layer']]['path']}`")
    joins = f.get("joins", []) or []
    if len(joins) == 1:
        L.append(f"- **Joins**: {joins[0]}")
    elif joins:
        L.append("- **Joins**:")
        L.extend(f"  - {j}" for j in joins)
    steps = f.get("included_steps", []) or []
    if steps or f.get("splits"):
        parts = [str(s) for s in sorted(steps)]
        parts += [f"{sp['step']} (actions {sp['action_indices']} のみ — split)"
                  for sp in f.get("splits", []) or []]
        L.append(f"- **Included original steps**: {', '.join(parts)}")
        L.append("- **Upstream lineage** (機械検証済 — plan_model lineage closure):")
        L.append("  | Included step | Reachable from Input(s) | Prev in this flow |")
        L.append("  |---|---|---|")
        parents: dict[str, list[str]] = {}
        for e in graph.edges:
            parents.setdefault(e.dst, []).append(graph.nodes[e.src].label)
        for key, gn in graph.nodes.items():
            if gn.role not in ("included", "split"):
                continue
            ins = ", ".join(sorted(
                graph.nodes[k].label for k in graph.reachable_inputs[key]))
            prev = " + ".join(parents.get(key, [])) or "—"
            L.append(f"  | {gn.label} | {ins} | {prev} |")
    if f.get("rename_back"):
        L.append("- **Rename-back (presentation rename)**:")
        L.append("  | internal name | original name |")
        L.append("  |---|---|")
        for rb in f["rename_back"]:
            L.append(f"  | {rb['from']} | {rb['to']} |")
    if f.get("incremental"):
        inc = f["incremental"]
        L.append(f"- **Incremental**: input=`{inc['input']}` "
                 f"control=`{inc['control_field']}` output_field=`{inc['output_field']}` "
                 "(append 出力 — full 再実行禁止、run は --incremental)")
    L.append(f"- **Description**:\n  {f.get('description', '')}")
    L.append("")
    return L


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--plan", required=True, type=Path)
    p.add_argument("--source", required=True, type=Path)
    p.add_argument("-o", "--output", required=True, type=Path)
    args = p.parse_args()

    plan = load_plan(args.plan)
    leftover = [k for k in plan if k.startswith("_")]
    if leftover:
        print(f"[render_plan] ERROR: skeleton TODO keys remain: {leftover} — "
              "finish the design and delete them.", file=sys.stderr)
        return 1
    source = read_source(args.source)
    resolver = StepResolver(source)
    issues, notes = validate_plan_with_source(plan, source)
    if issues:
        print(f"[render_plan] ERROR: plan validation failed ({len(issues)}):",
              file=sys.stderr)
        for i in issues:
            print(f"  - {i}", file=sys.stderr)
        return 1

    flows = plan["flows"]
    by_layer: dict[str, list[dict]] = {"staging": [], "intermediate": [], "marts": []}
    for f in flows:
        by_layer[f["layer"]].append(f)

    L: list[str] = [f"# Decomposition Plan: {plan['flow_name']}", ""]
    L += ["> Rendered from "
          f"`{args.plan.name}` by render_plan_md.py — edit the JSON, not this file.", ""]

    L += ["## Summary", ""]
    L.append(f"- 元フロー: {plan['source']['tfl_path']}"
             f"（{plan['source']['total_nodes']} ステップ）")
    L.append(f"- 新規成果物: {len(flows)} 個")
    for layer in ("staging", "intermediate", "marts"):
        if by_layer[layer]:
            names = ", ".join(x["name"] for x in by_layer[layer])
            L.append(f"  - {LAYER_LABEL[layer]}: {len(by_layer[layer])} 個（{names}）")
    L.append("- publish 粒度: **全層 (stg/int/marts) を Published DS として publish**。"
             "下流レイヤは上流レイヤの PDS を Input として参照")
    for n in notes:
        L.append(f"- 検証ノート: {n}")
    L.append("")

    L += ["## New .tfl files", ""]
    for layer in ("staging", "intermediate", "marts"):
        for f in by_layer[layer]:
            L += render_entry(f, resolver, plan)

    L += ["## Actions-level splits", ""]
    split_rows = [(f, sp) for f in flows for sp in (f.get("splits") or [])]
    if split_rows:
        L.append("| 元ノード | 分割先 .tfl | 残す actions | 備考 |")
        L.append("|---|---|---|---|")
        for f, sp in split_rows:
            L.append(f"| {resolver.label(sp['step'])} | {f['name']} "
                     f"(`{sp['new_name']}`) | {sp['action_indices']} "
                     f"| {sp.get('note', '—')} |")
    else:
        L.append("なし")
    L.append("")

    L += ["## Output mapping (original → decomposed)", ""]
    mapping = [(f.get("source_original_output_name"), f) for f in flows
               if f.get("source_original_output_name")]
    if mapping:
        L.append("| Original output PDS | Decomposed flow | Decomposed output PDS |")
        L.append("|---|---|---|")
        for orig, f in mapping:
            out_name = (f.get("output") or {}).get("name") or f["name"]
            L.append(f"| {orig} | {f['name']} | {out_name} |")
    else:
        L.append("_(元 output を引き継ぐ flow なし — comparator ペアなし)_")
    L.append("")

    L += ["## Target Tableau Cloud project layout", ""]
    L.append("| Subproject | LUID | Contains |")
    L.append("|---|---|---|")
    for grp, suffix in (("flow_projects", ".tfl"), ("ds_projects", " (PDS)")):
        for layer in ("staging", "intermediate", "marts"):
            proj = plan[grp][layer]
            names = ", ".join(x["name"] + (suffix if suffix == " (PDS)" else ".tfl")
                              for x in by_layer[layer]
                              if not (grp == "flow_projects"
                                      and x["kind"] == "pds_augment"))
            L.append(f"| `{proj['path']}` | `{proj['luid']}` | {names or '—'} |")
    L.append("")

    L += ["## Dependency DAG (Mermaid)", "", "### Before (元フロー、主要分岐点のみ)",
          "", "```mermaid", "graph TD"]
    L += render_before_dag(resolver, plan)
    L += ["```", "", "### After (分解後)", "", "```mermaid", "graph TD"]
    L += render_after_dag(plan, resolver)
    L += ["```", ""]

    L += ["## Migration order", ""]
    for i, wave in enumerate(flow_waves(plan), 1):
        parts = []
        for f in wave:
            if f.get("input_status") == "needs_provisioning":
                parts.append(f"{f['name']} (SKIP: provisioning 待ち)")
            elif f["kind"] == "pds_augment":
                parts.append(f"{f['name']} (augment publish のみ)")
            else:
                parts.append(f"{f['name']} (publish + run)")
        L.append(f"{i}. **Wave {i}**: {', '.join(parts)}（同 wave 内は並列可）")
    n = len(flow_waves(plan))
    L.append(f"{n + 1}. **検証**: prep-output-comparator で元 PDS との parity 確認")
    L.append(f"{n + 2}. **切替/廃止**: BI 参照先の切替後、旧フローをアーカイブ")
    L.append("")

    prov_flows = [f for f in flows if f.get("input_status") == "needs_provisioning"]
    if prov_flows:
        L += ["## Input provisioning required", ""]
        L.append("| Flow | Source | kind | 推奨整備 | 整備後の再開手順 |")
        L.append("|---|---|---|---|---|")
        for f in prov_flows:
            pv = f.get("provisioning") or {}
            L.append(f"| {f['name']} | {pv.get('source', '?')} | {pv.get('kind', '?')} "
                     f"| {pv.get('recommendation', 'TODO')} | {pv.get('resume', '—')} |")
        L.append("")

    alternatives = plan.get("alternatives", []) or []
    if alternatives:
        L += ["## Alternatives considered", ""]
        for alt in alternatives:
            L += [f"### {alt.get('title', '案')}", "", alt.get("body", ""), ""]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(L)
    args.output.write_text(text, encoding="utf-8")
    print(f"[render_plan] wrote {args.output} ({len(text):,} chars). "
          f"Validation: 0 issues, {len(notes)} note(s).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
